apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.clusterResourcesCM" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    benchmark: params
data:
  cluster_resources.json: |
    {
      "node_count": {{ .Values.resources.cluster.node_count }},
      "nodes_total_cpu": {{ .Values.resources.cluster.nodes_total_cpu_cores }},
      "nodes_total_memory": {{ .Values.resources.cluster.nodes_total_memory_mbytes }}
    }