apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.functionsPV" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    benchmark: functions
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /internal-svc-functions
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          # the node that provides svc-cell functions at '/internal-svc-functions'
          operator: In
          values:
          - {{ .Values.node_roles.observer }}
