apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.resultPV" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    benchmark: output
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /result
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          # the node that provides room for result at '/result'
          operator: In
          values:
          - {{ .Values.node_roles.observer }}
