# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

resources:
  cluster:
    node_count: 10
    nodes_total_cpu_cores: 100
    nodes_total_memory_mbytes: 160000
  node_target_utilization:
    mean_cpu: 0.2006
    mean_memory: 0.2708
  service_cell:
    base_cpu: 20
    base_memory: 60

node_roles:
  # the node that provides input dataset at '/dataset'
  # and provides svc-cell functions at '/internal-svc-functions'
  # and provides provides room for result at '/result'
  observer: node-2

benchmark:
  namespace: mubench
  cluster_domain: cluster
  dns_resolver: kube-dns.kube-system.svc.cluster.local
  scheduler: default-scheduler
  deployment_headstart_seconds: 30

  service_cell:
    template:
      image:
        name: lujoka/mub-cell
        version: 0.1.1
      replicas: 1
      ingress: false
      service_monitor: true
    api_path: /api/v1
    gunicorn:
      workers: 4
      threads: 16
    loader:
      factor_cpu: 5.0
      thread_pool_size: 1
      trials: 1
      factor_memory: 5.0
      memory_io: 500
      disk_write_block_count: 1000
      disk_write_block_size: 1024
      mean_response_size: 11

runner:
  image:
    name: lujoka/mub-csv-runner
    version: latest
  extraArgs:
    - "--log-level"
    - "INFO"
  threadpool_size: 10
  ttlMinutesAfterFinished: 600

workmodel_gen:
  image:
    name: lujoka/mub-workmodel-gen
    version: latest
  extraArgs:
    - "--log-level"
    - "DEBUG"

templater:
  image:
    name: lujoka/mub-k8s-templater
    version: latest
  extraArgs:
    - "--log-level"
    - "DEBUG"
