apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.clusterResourcesCM" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    benchmark: params
data:
  cluster_ressources.json: |
    {
      "node_count": {{ .Values.resources.cluster.node_count }},
      "nodes_total_cpu": {{ .Values.resources.cluster.nodes_total_cpu_cores }},
      "nodes_total_memory": {{ .Values.resources.cluster.nodes_total_memory_mbytes }},
      "target_mean_cpu": {{ .Values.resources.node_target_utilization.mean_cpu }},
      "target_mean_memory": {{ .Values.resources.node_target_utilization.mean_memory }}
    }