apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.functionsPV" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    benchmark: functions
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      benchmark: functions
