apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.resultPV" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    benchmark: output
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      benchmark: output
